<?php
global $api_mapping_my;
$api_mapping_my = array(
  'getUserBasic' => 'gub',
  'getUserEducation' => 'gue',
  'setUserBasic' => 'sub',
  'getUserIcon' => 'gui',
  'getFriLoginFollowed' => 'gflf',
  'getFriFollowed' => 'gff',
  'getUserBriefInfo' => 'gubi',
  'getUserDetailInfo' => 'gudi',
  'incUserPoint' => 'iup',
  'getUserPoint' => 'gup',
  'incPlayTime' => 'ipt',
  'getPlayTime' => 'gpt',
  'getUserPointIcon' => 'gupi',
  'setNewUserBobusPoint' => 'snubp',
  'getUserWorks' => 'guw',
  'getUserWorkCount' => 'guwc',
  'getFlowerNum' => 'gfn',
  'getFlowerID' => 'gfi',
  'getUserPlayedGames' => 'gupg',
  'getUserPlayedGamesCount' => 'gupgc',
  'saveUserPlayedGame' => 'supg',
  'sendMessage' => 'sm',
  'addFollow' => 'addfl',
  'sendMail' => 'sem',
  'getCity' => 'gct',
  'requestPet' => 'reqp',
  'setUserKbean' => 'suk',
  'getUserKbean' => 'guk',
  'assignRandomUicon' => 'aru',
  'savePlayedGameInfo' => 'spgi',
  'remotePassSetting' => 'rps',
  'remoteSaveSafeCode' => 'rssc',
  'remoteAddProtectedQQ' => 'rapq',
  'remoteAddProtectedEmail' => 'rape',
  'remoteUpdateProtectedEmail' => 'rupe',
  'remoteUpdateProtectedQQ' => 'rupq',
  'getSchool' => 'gsh',
  'setUserSchool' => 'sus',
  'getUserSchool' => 'gus',
  'increasePointByLoginOrRegister' => 'ipblor',
  'getPromptNotices' => 'gpn',
  'getUnreadMessageTotal' => 'gumt',
  'getUnreadMessages' => 'gums',
  'getUserFollow' => 'guf',
  'saveFavedGame' => 'sfg',
);


global $api_mapping_passport;
$api_mapping_passport = array(
    'getForgotPassResetCode' => 'gfprc', 'getForgotPassResetCodeByIdentity' => 'gfprci', 'updateForgotPass' => 'ufp',
    'updatePassword' => 'up', 'setUserPassword' => 'sup', 'setPasswordByUid' => 'spbu',
    'updateIdentity' => 'ui', 'checkAccount' => 'ca', 'modifyUserPassword' => 'mup',
    'checkForgotPassCode' => 'cfpc', 'checkUserByUserId' => 'cubui', 'checkUserByUsername' => 'cubu',
    'searchUsernameReturnUId' => 'suru', 'getQuestionByUsername' => 'gqbu', 'getQuestionByUid' => 'gqbui',
    'getQaByDate' => 'gqbd', 'getUserInfo' => 'gui', 'getUsernameById' => 'gubi',
    'getUserInfoAll' => 'guia', 'getUserBasicInfo' => 'gubin', 'getUserIcon' => 'guic',
    'getValidateCodeByUserid' => 'gvcbui', 'isLogin' => 'il', 'getLoginInfo' => 'gli',
    'getDownloadAccountInfo' => 'gdai', 'getUidOfUser' => 'guou', 'login' => 'li', 'login_unify' => 'liu',
    'getLoginDetails' => 'gld', 'checkUsernameExists' => 'cune', 'checkEmailExists' => 'cee',
    'checkUidExists' => 'cue', 'checkNicknameExists' => 'cne', 'register' => 'rt',
    'registerByEmail' => 'rbe', 'registerByQq' => 'rbq', 'setUserDetail' => 'sud',
    'setUserNickname' => 'sun', 'getUserDetail' => 'gud', 'getUserNickname' => 'gun',
    'logout' => 'lo', 'getNumberOfUsers' => 'gnou', 'regAlias' => 'ra',
    'nicknameAlias' => 'nna', 'qaAlias' => 'qa', 'loginAlias' => 'la',
    'forgotAlias' => 'fa', 'updatePAlias' => 'upa', 'forgotPassAlias' => 'fpa',
    'updatePassAlias' => 'upa', 'getQuestionList' => 'gql', 'setQA' => 'sq',
    'addNoLogin' => 'anl', 'delNoLogin' => 'dnl', 'isNoLogin' => 'inl',
    'addIpNoLogin' => 'ainl', 'delIpNoLogin' => 'dinl', 'isIpNoLogin' => 'iinl',
    'getUserTotal' => 'gut', 'getRegTime' => 'grt', 'online' => 'ol',
    'getKKByIdentity' => 'gkbi', 'listKK' => 'lk', 'updateKK' => 'uk',
    'getAuthCode' => 'gac', 'checkAuthCode' => 'cac', 'getSimpleCaptcha' => 'gsc',
    'checkSimpleCaptcha' => 'cscc', 'validAuthCode' => 'vac', 'setProtectEmail' => 'spe',
    'sendProtectEmailActivation' => 'spea', 'updateProtectEmail' => 'upe', 'verifyUserProtectEmail' => 'vupe',
    'verifyProtectEmail' => 'vpe', 'setProtectQQ' => 'spq', 'sendProtectQQActivation' => 'spqa',
    'updateProtectQQ' => 'upq', 'verifyUserProtectQQ' => 'vupq', 'verifyProtectQQ' => 'vpq',
    'verifyProtectCode' => 'vpc', 'getProtectHashedCode' => 'gphc', 'getUserPassProtectSettings' => 'gupps',
    'isProtectEmailActivated' => 'ipea', 'isProtectQQActivated' => 'ipqa', 'protectVerificationAlias' => 'pva',
    'isSafeCodeExists' => 'isce', 'saveSafeCode' => 'ssc', 'checkSafeCode' => 'csc',
    'sendGetPwdEmail' => 'sgpe', 'isResetCodeValid' => 'ircv', 'checkPwdFormat' => 'cpf',
    'isNewRegUser' => 'inru', 'bindQqToUser' => 'bqtu', 'qqlogin' => 'ql',
    'isQqBind' => 'iqb', 'get_access_token' => 'gat', 'get_request_token' => 'grtk',
    'get_qq_userinfo' => 'gqui', 'generateQqPwd' => 'gqp', 'isAjaxRequest' => 'iar',
    'setSession' => 'ss', 'getSession' => 'gs', 'delSession' => 'ds',
    'checkIdentityExists' => 'cie', 'getRegDetail' => 'grd', 'getRegDetailCount' => 'grdc',

);


global $api_setcookie;
$api_setcookie = array (
  'login' => 'login',
  'login_unify' => 'login_unify',
  'register' => 'register',
  'registerByEmail' => 'registerByEmail',
  'updateIdentity' => 'updateIdentity',
  'registerByQq' => 'registerByQq',
  'setUserNickname' => 'setUserNickname',
  'logout' => 'logout',
  'getSimpleCaptcha' => 'getSimpleCaptcha',
  'setSession' => 'setSession',
  'delSession' => 'delSession',
);
